background #282325
foreground #ebebf0
cursor #ebbcba
cursor_text_color #141418
selection_background #625152
selection_foreground #ebebf0
url_color #ebbcba
color0 #353032
color1 #d05555
color2 #55d055
color3 #d0bb55
color4 #5555d0
color5 #d055d0
color6 #55d0d0
color7 #96969e
color8 #6a686e
color9 #f1cece
color10 #cef1ce
color11 #f1ebce
color12 #cecef1
color13 #f1cef1
color14 #cef1f1
color15 #ebebf0
active_tab_foreground #141418
active_tab_background #ebbcba
inactive_tab_foreground #96969e
inactive_tab_background #353032
