# Fyzenor Theme: Matugen Generated

[colors]
dir = "#dfb8f6"
file = "#e9e0e8"
sel_bg = "#4b454d"
media = "#f4b7ba"
image = "#d2c1d9"
border = "#968e98"
success = "#f3daff"
error = "#ffb4ab"
multi = "#663b3d"
pin_bg = "#4f4256"
pin_border = "#dfb8f6"
sec_sel_bg = "#161217"
