# Fyzenor Theme: Matugen Generated

[colors]
dir = "#98ccf9"
file = "#e0e3e8"
sel_bg = "#42474d"
media = "#d0bfe7"
image = "#b8c8d9"
border = "#8c9198"
success = "#cbe6ff"
error = "#ffb4ab"
multi = "#4e4162"
pin_bg = "#394856"
pin_border = "#98ccf9"
sec_sel_bg = "#101417"
