# Fyzenor Theme: Matugen Generated

[colors]
dir = "#faba73"
file = "#eee0d5"
sel_bg = "#50453a"
media = "#becc9c"
image = "#e0c1a3"
border = "#9d8e81"
success = "#ffddbb"
error = "#ffb4ab"
multi = "#3f4b26"
pin_bg = "#58432c"
pin_border = "#faba73"
sec_sel_bg = "#19120c"
